# docker-compose.yml
services:
  crosswatch:
    image: "ghcr.io/cenodude/crosswatch:latest"
    container_name: "crosswatch"
    ports:
      - "8787:8787"
    environment:
      TZ: "Europe/Amsterdam"
    volumes:
      - type: "volume"
        source: "crosswatch_config"
        target: "/config"
    restart: "unless-stopped"

volumes:
  crosswatch_config:
