# docker-compose.yml
services:
  crosswatch:
    image: "ghcr.io/cenodude/crosswatch:latest"
    container_name: "crosswatch"
    ports:
      - "${LAN_IP:-127.0.0.1}:8787:8787"
    environment:
      TZ: "${TZ:-Etc/UTC}"
    # Uncomment the volume type for your deployment:
    # volumes:
    #   - type: "volume"
    #     source: "crosswatch_config"
    #     target: "/config/"
    #   - type: "bind"
    #     source: "./crosswatch/config/"
    #     target: "/config/"
    restart: "unless-stopped"

volumes:
  crosswatch_config:
